name: "Translation"

on:
  push:
    branches:
      - dev

permissions:
  contents: write

jobs:
  translate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          ref: dev
      - name: Sync main with dev (force rebase)
        run: |
          git fetch origin dev
          git checkout dev
          # S'assurer d'être bien sur dev
          git pull origin dev
          
          # Créer ou réinitialiser main à dev
          git checkout main || git checkout -b main
          git reset --hard origin/dev

          # Push forcé de main
          git push origin main --force

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Cache Hugging Face models
        uses: actions/cache@v3
        with:
          path: ~/.cache/huggingface
          key: ${{ runner.os }}-huggingface-${{ hashFiles('translate_hf.py') }}
          restore-keys: |
            ${{ runner.os }}-huggingface-

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run translation
        run: |
          mkdir translations_tmp
          find content/posts -type f -name "*.md" ! -name "*.fr.md" -print0 | while IFS= read -r -d '' file; do
            echo "Translating $file"
            python3 translate_hf.py "$file"
            echo "Translating Done"
          done

      - name: Commit translations to main
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"

          git add content/posts
          git diff --cached --quiet || git commit -m "Auto-translate new posts (EN→FR)"
          git push -f origin main